#{ gemspec.name }#{ " - #{ gemspec.summary }" if gemspec.summary }
===

#{ gemspec.description }

For example this document was rendered from [readme.md.rbs](https://github.com/lpogic/rebus/blob/main/doc/draft/readme.md.rbs) template.

Installation
---
```
gem install #{ gemspec.name }
```

Basics
---

Rules are:
- input is interpreted line by line
- there are 3 different line types recognized by the following prefixes:
  - `# `  - a comment line skipped during compilation
  - `$ `  - a code line evaluated during compilation
  - any other - a string line with possible interpolated code (see Ruby string interpolation rules)

#### Sample (stealed and translated from [ERB documentation](https://ruby-doc.org/stdlib-3.1.0/libdoc/erb/rdoc/ERB.html#class-ERB-label-Ruby+in+HTML)):


Template(Rebus - HTML):
```HTML
#{ File.read "sample/a0.rbs" }
```

Source code(Ruby):
#{ code.call "sample/a0.rb" }

Output(HTML):
```HTML
<html>
  <head><title>Ruby Toys -- Rubysapien</title></head>
  <body>

    <h1>Rubysapien (TZ-1002)</h1>
    <p>Geek's Best Friend!  Responds to Ruby commands...</p>

    <ul>
        <li><b>Listens for verbal commands in the Ruby language!</b></li>
        <li><b>Ignores Perl, Java, and all C variants.</b></li>
        <li><b>Karate-Chop Action!!!</b></li>
        <li><b>Matz signature on left leg.</b></li>
        <li><b>Gem studded eyes... Rubies, of course!</b></li>
    </ul>

    <p>
         Call for a price, today!
    </p>

  </body>
</html>
```

Usage
---
[Wiki](https://github.com/lpogic/rebus/blob/main/doc/wiki/README.md)

Authors
---
#{ gemspec.authors.zip(Array(gemspec.email)).map{ "- #{_1} (#{_2})" }.join("\n") }
